// Source: /Users/xiaopingfeng/Projects/cyberai/targets/poppler-26.04.0/poppler/GfxFont.cc
// Segment 2/20



static const Base14FontMapEntry base14FontMap[] = { { .altName = "Arial", .base14Name = "Helvetica" },
                                                    { .altName = "Arial,Bold", .base14Name = "Helvetica-Bold" },
                                                    { .altName = "Arial,BoldItalic", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Arial,Italic", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "Arial-Bold", .base14Name = "Helvetica-Bold" },
                                                    { .altName = "Arial-BoldItalic", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Arial-BoldItalicMT", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Arial-BoldMT", .base14Name = "Helvetica-Bold" },
                                                    { .altName = "Arial-Italic", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "Arial-ItalicMT", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "ArialMT", .base14Name = "Helvetica" },
                                                    { .altName = "Courier", .base14Name = "Courier" },
                                                    { .altName = "Courier,Bold", .base14Name = "Courier-Bold" },
                                                    { .altName = "Courier,BoldItalic", .base14Name = "Courier-BoldOblique" },
                                                    { .altName = "Courier,Italic", .base14Name = "Courier-Oblique" },
                                                    { .altName = "Courier-Bold", .base14Name = "Courier-Bold" },
                                                    { .altName = "Courier-BoldOblique", .base14Name = "Courier-BoldOblique" },
                                                    { .altName = "Courier-Oblique", .base14Name = "Courier-Oblique" },
                                                    { .altName = "CourierNew", .base14Name = "Courier" },
                                                    { .altName = "CourierNew,Bold", .base14Name = "Courier-Bold" },
                                                    { .altName = "CourierNew,BoldItalic", .base14Name = "Courier-BoldOblique" },
                                                    { .altName = "CourierNew,Italic", .base14Name = "Courier-Oblique" },
                                                    { .altName = "CourierNew-Bold", .base14Name = "Courier-Bold" },
                                                    { .altName = "CourierNew-BoldItalic", .base14Name = "Courier-BoldOblique" },
                                                    { .altName = "CourierNew-Italic", .base14Name = "Courier-Oblique" },
                                                    { .altName = "CourierNewPS-BoldItalicMT", .base14Name = "Courier-BoldOblique" },
                                                    { .altName = "CourierNewPS-BoldMT", .base14Name = "Courier-Bold" },
                                                    { .altName = "CourierNewPS-ItalicMT", .base14Name = "Courier-Oblique" },
                                                    { .altName = "CourierNewPSMT", .base14Name = "Courier" },
                                                    { .altName = "Helvetica", .base14Name = "Helvetica" },
                                                    { .altName = "Helvetica,Bold", .base14Name = "Helvetica-Bold" },
                                                    { .altName = "Helvetica,BoldItalic", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Helvetica,Italic", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "Helvetica-Bold", .base14Name = "Helvetica-Bold" },
                                                    { .altName = "Helvetica-BoldItalic", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Helvetica-BoldOblique", .base14Name = "Helvetica-BoldOblique" },
                                                    { .altName = "Helvetica-Italic", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "Helvetica-Oblique", .base14Name = "Helvetica-Oblique" },
                                                    { .altName = "Symbol", .base14Name = "Symbol" },
                                                    { .altName = "Symbol,Bold", .base14Name = "Symbol" },
                                                    { .altName = "Symbol,BoldItalic", .base14Name = "Symbol" },
                                                    { .altName = "Symbol,Italic", .base14Name = "Symbol" },
                                          